# Pytorch
## Tensor
1. scalar: 0维，数字
2. vector: 1维
3. matrix: 2维
4. tensor: 3维或更多

为了简便起见，我们把vector和matrix也叫做tensor.  
tensor()既能创建scalar也能创建tensor. Pytorch里的tensor和numpy很像。

In [3]:
import torch
scalar = torch.tensor(3.14159)
vector = torch.tensor([1,2,3])
matrix = torch.ones((2,3), dtype=torch.float)
tensor = torch.randn((2,3,4), dtype=torch.float)
print(tensor)
print(tensor.size(), tensor.shape)
print(vector.size(), vector.shape)
print(scalar.size(), scalar.shape)

tensor([[[-1.3585,  1.2498,  0.9362, -0.4114],
         [ 0.9053, -0.4949, -0.8376,  1.5091],
         [-0.1211,  2.6087, -0.0129,  1.9131]],

        [[ 1.3920,  0.5701,  0.3690, -0.6954],
         [ 1.0588, -0.5522, -1.3058,  0.0103],
         [-0.9186, -1.0471, -0.6099,  2.0403]]])
torch.Size([2, 3, 4]) torch.Size([2, 3, 4])
torch.Size([3]) torch.Size([3])
torch.Size([]) torch.Size([])


In [5]:
same_matrix = matrix.view(1,6)
print(same_matrix)
same_matrix[0,1]=2
print(same_matrix)
another_matrix = same_matrix.clone().detach() # duplicate the data
print(another_matrix)

tensor([[1., 2., 1., 1., 1., 1.]])
tensor([[1., 2., 1., 1., 1., 1.]])
tensor([[1., 2., 1., 1., 1., 1.]])
